In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
# import csv

In [2]:
data = pd.read_csv('건강검진정보-1.csv', engine = 'python')
data.head()

,가입자일련번호,성별코드,연령대코드,신장,체중,허리둘레,수축기혈압,이완기혈압,혈당,총콜레스테롤,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,흡연상태,체지방률,골격근량,엉덩이둘레
0,1,1,10,175.0,75.0,86.0,140.0,90.0,91.0,263.0,196.0,46.0,177.0,16.0,1.0,3.0,18.3174,34.8408,939.9140
1,2,2,11,160.0,65.0,85.0,138.0,80.0,105.0,185.0,262.0,35.0,122.0,13.1,1.0,1.0,21.8930,28.5128,896.4777
2,3,2,11,150.0,55.0,80.0,138.0,88.0,93.0,246.0,186.0,59.0,150.0,13.6,1.0,1.0,22.2150,23.5983,848.2792
3,4,1,12,175.0,70.0,85.0,124.0,76.0,93.0,179.0,79.0,40.0,123.0,16.8,1.0,2.0,16.7492,33.2789,911.6084
4,5,2,6,160.0,50.0,67.0,121.0,68.0,96.0,223.0,104.0,72.0,130.0,12.8,1.0,1.0,13.8547,24.7200,823.7647

In [3]:
data = data.set_index('가입자일련번호')

In [4]:
data_male = data[data['성별코드']==1]
data_male.head()

,성별코드,연령대코드,신장,체중,허리둘레,수축기혈압,이완기혈압,혈당,총콜레스테롤,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,흡연상태,체지방률,골격근량,엉덩이둘레
가입자일련번호,,,,,,,,,,,,,,,,,,
1,1,10,175.0,75.0,86.0,140.0,90.0,91.0,263.0,196.0,46.0,177.0,16.0,1.0,3.0,18.3174,34.8408,939.9140
4,1,12,175.0,70.0,85.0,124.0,76.0,93.0,179.0,79.0,40.0,123.0,16.8,1.0,2.0,16.7492,33.2789,911.6084
6,1,9,170.0,55.0,64.0,124.0,79.0,90.0,319.0,45.0,53.0,257.0,15.8,1.0,1.0,8.6160,29.6215,819.4938
7,1,10,175.0,70.0,90.0,114.0,76.0,85.0,207.0,93.0,50.0,138.0,13.9,1.0,3.0,19.5168,31.9352,935.1275
9,1,16,165.0,60.0,74.0,127.0,69.0,86.0,210.0,109.0,59.0,129.0,13.5,1.0,1.0,13.2824,30.2722,827.3977

In [5]:
data_female = data[data['성별코드']==2]
data_female.head()

,성별코드,연령대코드,신장,체중,허리둘레,수축기혈압,이완기혈압,혈당,총콜레스테롤,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,흡연상태,체지방률,골격근량,엉덩이둘레
가입자일련번호,,,,,,,,,,,,,,,,,,
2,2,11,160.0,65.0,85.0,138.0,80.0,105.0,185.0,262.0,35.0,122.0,13.1,1.0,1.0,21.8930,28.5128,896.4777
3,2,11,150.0,55.0,80.0,138.0,88.0,93.0,246.0,186.0,59.0,150.0,13.6,1.0,1.0,22.2150,23.5983,848.2792
5,2,6,160.0,50.0,67.0,121.0,68.0,96.0,223.0,104.0,72.0,130.0,12.8,1.0,1.0,13.8547,24.7200,823.7647
8,2,16,155.0,60.0,81.0,130.0,70.0,101.0,174.0,89.0,48.0,108.0,13.0,1.0,1.0,19.9376,27.2709,843.9022
12,2,6,155.0,50.0,66.0,109.0,66.0,85.0,198.0,117.0,82.0,92.0,13.6,1.0,1.0,15.2176,24.0964,819.6127

In [6]:
data_male['신장'].head()

가입자일련번호
1    175.0
4    175.0
6    170.0
7    175.0
9    165.0
Name: 신장, dtype: float64

In [7]:
np.std(data_male['신장'])

6.701861489912905

In [8]:
표준신장 = (data_male['신장']-np.mean(data_male['신장']))/np.std(data_male['신장'])

In [9]:
표준체중 = (data_male['체중']-np.mean(data_male['체중']))/np.std(data_male['체중'])

In [10]:
표준허리둘레 = (data_male['허리둘레']-np.mean(data_male['허리둘레']))/np.std(data_male['허리둘레'])
표준체지방률 = (data_male['체지방률']-np.mean(data_male['체지방률']))/np.std(data_male['체지방률'])
표준골격근량 = (data_male['골격근량']-np.mean(data_male['골격근량']))/np.std(data_male['골격근량'])
표준엉덩이둘레 = (data_male['엉덩이둘레']-np.mean(data_male['엉덩이둘레']))/np.std(data_male['엉덩이둘레'])

In [11]:
data_male['신장'] = 표준신장 + 10
data_male['체중'] = 표준체중 + 10
data_male['허리둘레'] = 표준허리둘레 + 10
data_male['체지방률'] = 표준체지방률 + 10
data_male['골격근량'] = 표준골격근량 + 10
data_male['엉덩이둘레'] = 표준엉덩이둘레 + 10

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
data_male.head()

,성별코드,연령대코드,신장,체중,허리둘레,수축기혈압,이완기혈압,혈당,총콜레스테롤,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,흡연상태,체지방률,골격근량,엉덩이둘레
가입자일련번호,,,,,,,,,,,,,,,,,,
1,1,10,10.944087,10.440557,10.131985,140.0,90.0,91.0,263.0,196.0,46.0,177.0,16.0,1.0,3.0,9.771078,10.625064,10.363693
4,1,12,10.944087,10.006399,10.022048,124.0,76.0,93.0,179.0,79.0,40.0,123.0,16.8,1.0,2.0,9.465413,10.296124,9.908017
6,1,9,10.198026,8.703923,7.713381,124.0,79.0,90.0,319.0,45.0,53.0,257.0,15.8,1.0,1.0,7.880133,9.525866,8.425116
7,1,10,10.944087,10.006399,10.571731,114.0,76.0,85.0,207.0,93.0,50.0,138.0,13.9,1.0,3.0,10.004859,10.013137,10.286638
9,1,16,9.451965,9.138082,8.812746,127.0,69.0,86.0,210.0,109.0,59.0,129.0,13.5,1.0,1.0,8.789683,9.662905,8.552356

In [13]:
data_male = data_male.dropna()
data_male.head()

,성별코드,연령대코드,신장,체중,허리둘레,수축기혈압,이완기혈압,혈당,총콜레스테롤,트리글리세라이드,HDL콜레스테롤,LDL콜레스테롤,혈색소,요단백,흡연상태,체지방률,골격근량,엉덩이둘레
가입자일련번호,,,,,,,,,,,,,,,,,,
1,1,10,10.944087,10.440557,10.131985,140.0,90.0,91.0,263.0,196.0,46.0,177.0,16.0,1.0,3.0,9.771078,10.625064,10.363693
4,1,12,10.944087,10.006399,10.022048,124.0,76.0,93.0,179.0,79.0,40.0,123.0,16.8,1.0,2.0,9.465413,10.296124,9.908017
6,1,9,10.198026,8.703923,7.713381,124.0,79.0,90.0,319.0,45.0,53.0,257.0,15.8,1.0,1.0,7.880133,9.525866,8.425116
7,1,10,10.944087,10.006399,10.571731,114.0,76.0,85.0,207.0,93.0,50.0,138.0,13.9,1.0,3.0,10.004859,10.013137,10.286638
9,1,16,9.451965,9.138082,8.812746,127.0,69.0,86.0,210.0,109.0,59.0,129.0,13.5,1.0,1.0,8.789683,9.662905,8.552356

In [14]:
data_male['혈당'][data_male['혈당']<100] = 1
data_male['혈당'][data_male['혈당']>=126] = 3
data_male['혈당'][data_male['혈당'].between(100, 125)] = 2
data_male['혈당']

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

가입자일련번호
1         1.0
4         1.0
6         1.0
7         1.0
9         1.0
10        2.0
11        1.0
13        2.0
16        1.0
17        2.0
18        1.0
19        2.0
21        1.0
22        1.0
23        1.0
25        2.0
26        1.0
27        1.0
28        1.0
30        1.0
31        2.0
32        1.0
33        3.0
36        2.0
38        1.0
40        1.0
42        1.0
43        2.0
49        1.0
57        1.0
         ...
999944    1.0
999945    3.0
999947    2.0
999950    2.0
999952    1.0
999955    1.0
999956    1.0
999957    3.0
999958    1.0
999960    1.0
999962    1.0
999966    1.0
999968    1.0
999969    2.0
999970    1.0
999974    1.0
999976    1.0
999978    1.0
999979    1.0
999980    1.0
999981    2.0
999984    2.0
999985    2.0
999987    1.0
999988    3.0
999989    3.0
999993    2.0
999995    3.0
999996    2.0
999998    2.0
Name: 혈당, Length: 528891, dtype: float64

In [15]:
data_male['수축기혈압'][data_male['수축기혈압']<120] = 1
data_male['수축기혈압'][data_male['수축기혈압']>=160] = 4
data_male['수축기혈압'][data_male['수축기혈압'].between(120, 139)] = 2
data_male['수축기혈압'][data_male['수축기혈압'].between(140, 159)] = 3
data_male['수축기혈압']

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

가입자일련번호
1         3.0
4         2.0
6         2.0
7         1.0
9         2.0
10        1.0
11        2.0
13        2.0
16        2.0
17        2.0
18        1.0
19        2.0
21        2.0
22        1.0
23        1.0
25        3.0
26        2.0
27        2.0
28        2.0
30        2.0
31        3.0
32        1.0
33        1.0
36        2.0
38        2.0
40        3.0
42        1.0
43        2.0
49        3.0
57        2.0
         ...
999944    1.0
999945    2.0
999947    2.0
999950    2.0
999952    2.0
999955    1.0
999956    2.0
999957    1.0
999958    1.0
999960    1.0
999962    1.0
999966    1.0
999968    3.0
999969    3.0
999970    1.0
999974    2.0
999976    4.0
999978    2.0
999979    2.0
999980    1.0
999981    3.0
999984    3.0
999985    2.0
999987    1.0
999988    2.0
999989    2.0
999993    2.0
999995    1.0
999996    1.0
999998    1.0
Name: 수축기혈압, Length: 528891, dtype: float64

In [16]:
data_male['이완기혈압'][data_male['이완기혈압']<80] = 1
data_male['이완기혈압'][data_male['이완기혈압']>=100] = 4
data_male['이완기혈압'][data_male['이완기혈압'].between(80, 89)] = 2
data_male['이완기혈압'][data_male['이완기혈압'].between(90, 99)] = 3
data_male['이완기혈압']

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

가입자일련번호
1         3.0
4         1.0
6         1.0
7         1.0
9         1.0
10        1.0
11        2.0
13        2.0
16        2.0
17        1.0
18        1.0
19        2.0
21        2.0
22        1.0
23        1.0
25        2.0
26        2.0
27        1.0
28        2.0
30        1.0
31        3.0
32        1.0
33        1.0
36        2.0
38        2.0
40        3.0
42        1.0
43        2.0
49        3.0
57        2.0
         ...
999944    1.0
999945    1.0
999947    2.0
999950    2.0
999952    1.0
999955    1.0
999956    2.0
999957    2.0
999958    1.0
999960    1.0
999962    1.0
999966    1.0
999968    3.0
999969    2.0
999970    1.0
999974    3.0
999976    3.0
999978    1.0
999979    1.0
999980    1.0
999981    1.0
999984    2.0
999985    1.0
999987    1.0
999988    2.0
999989    1.0
999993    2.0
999995    1.0
999996    1.0
999998    1.0
Name: 이완기혈압, Length: 528891, dtype: float64

In [17]:
data_male['총콜레스테롤'][data_male['총콜레스테롤']<200] = 1
data_male['총콜레스테롤'][data_male['총콜레스테롤']>=240] = 3
data_male['총콜레스테롤'][data_male['총콜레스테롤'].between(200, 239)] = 2
data_male['총콜레스테롤']

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

가입자일련번호
1         3.0
4         1.0
6         3.0
7         2.0
9         2.0
10        1.0
11        2.0
13        2.0
16        1.0
17        1.0
18        2.0
19        1.0
21        2.0
22        2.0
23        2.0
25        2.0
26        1.0
27        1.0
28        1.0
30        2.0
31        2.0
32        1.0
33        1.0
36        2.0
38        1.0
40        2.0
42        1.0
43        2.0
49        1.0
57        1.0
         ...
999944    1.0
999945    1.0
999947    1.0
999950    1.0
999952    1.0
999955    1.0
999956    2.0
999957    1.0
999958    1.0
999960    1.0
999962    1.0
999966    2.0
999968    2.0
999969    2.0
999970    2.0
999974    1.0
999976    1.0
999978    3.0
999979    1.0
999980    1.0
999981    1.0
999984    1.0
999985    3.0
999987    2.0
999988    1.0
999989    3.0
999993    1.0
999995    1.0
999996    1.0
999998    1.0
Name: 총콜레스테롤, Length: 528891, dtype: float64

In [18]:
data_male['LDL콜레스테롤'][data_male['LDL콜레스테롤']<100] = 1
data_male['LDL콜레스테롤'][data_male['LDL콜레스테롤']>=160] = 4
data_male['LDL콜레스테롤'][data_male['LDL콜레스테롤'].between(100, 129)] = 2
data_male['LDL콜레스테롤'][data_male['LDL콜레스테롤'].between(130, 159)] = 3
data_male['LDL콜레스테롤']

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

가입자일련번호
1         4.0
4         2.0
6         4.0
7         3.0
9         2.0
10        1.0
11        1.0
13        3.0
16        1.0
17        2.0
18        3.0
19        3.0
21        1.0
22        4.0
23        3.0
25        3.0
26        1.0
27        1.0
28        2.0
30        3.0
31        2.0
32        3.0
33        1.0
36        4.0
38        2.0
40        2.0
42        2.0
43        1.0
49        1.0
57        1.0
         ...
999944    2.0
999945    1.0
999947    1.0
999950    2.0
999952    2.0
999955    2.0
999956    2.0
999957    1.0
999958    2.0
999960    1.0
999962    1.0
999966    3.0
999968    3.0
999969    2.0
999970    2.0
999974    2.0
999976    1.0
999978    4.0
999979    1.0
999980    1.0
999981    2.0
999984    2.0
999985    4.0
999987    2.0
999988    1.0
999989    1.0
999993    1.0
999995    2.0
999996    1.0
999998    2.0
Name: LDL콜레스테롤, Length: 528891, dtype: float64

In [19]:
data_male['HDL콜레스테롤'][data_male['HDL콜레스테롤']<40] = 1
data_male['HDL콜레스테롤'][data_male['HDL콜레스테롤']>=60] = 3
data_male['HDL콜레스테롤'][data_male['HDL콜레스테롤'].between(40, 59)] = 2
data_male['HDL콜레스테롤']

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

가입자일련번호
1         2.0
4         2.0
6         2.0
7         2.0
9         2.0
10        2.0
11        2.0
13        2.0
16        3.0
17        2.0
18        2.0
19        2.0
21        3.0
22        2.0
23        1.0
25        2.0
26        3.0
27        1.0
28        3.0
30        2.0
31        3.0
32        2.0
33        2.0
36        1.0
38        2.0
40        2.0
42        1.0
43        3.0
49        2.0
57        2.0
         ...
999944    3.0
999945    2.0
999947    1.0
999950    2.0
999952    2.0
999955    2.0
999956    3.0
999957    3.0
999958    2.0
999960    2.0
999962    2.0
999966    3.0
999968    2.0
999969    2.0
999970    3.0
999974    2.0
999976    1.0
999978    2.0
999979    2.0
999980    1.0
999981    2.0
999984    1.0
999985    2.0
999987    2.0
999988    3.0
999989    1.0
999993    2.0
999995    2.0
999996    1.0
999998    2.0
Name: HDL콜레스테롤, Length: 528891, dtype: float64

In [20]:
data_male['혈색소'][data_male['혈색소']<13] = 2
data_male['혈색소'][data_male['혈색소']>=13] = 1
data_male['혈색소']

C:\Users\Home\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

가입자일련번호
1         1.0
4         1.0
6         1.0
7         1.0
9         1.0
10        1.0
11        1.0
13        1.0
16        1.0
17        1.0
18        1.0
19        1.0
21        1.0
22        1.0
23        1.0
25        1.0
26        1.0
27        2.0
28        1.0
30        1.0
31        1.0
32        1.0
33        1.0
36        1.0
38        1.0
40        1.0
42        1.0
43        1.0
49        1.0
57        1.0
         ...
999944    1.0
999945    1.0
999947    1.0
999950    1.0
999952    1.0
999955    1.0
999956    1.0
999957    1.0
999958    1.0
999960    1.0
999962    1.0
999966    1.0
999968    1.0
999969    1.0
999970    1.0
999974    1.0
999976    1.0
999978    1.0
999979    1.0
999980    1.0
999981    2.0
999984    1.0
999985    1.0
999987    1.0
999988    1.0
999989    1.0
999993    1.0
999995    1.0
999996    1.0
999998    1.0
Name: 혈색소, Length: 528891, dtype: float64

In [21]:
male_array_1 = np.array(data_male.loc[:, ['연령대코드','신장', '체중', '허리둘레','흡연상태','체지방률']])
male_array_1

array([[10.        , 10.94408733, 10.44055703, 10.13198481,  3.        ,
         9.77107833],
       [12.        , 10.94408733, 10.00639853, 10.02204825,  2.        ,
         9.4654131 ],
       [ 9.        , 10.19802596,  8.70392301,  7.7133806 ,  1.        ,
         7.88013285],
       ...,
       [16.        , 10.19802596,  8.70392301,  8.37299993,  1.        ,
         7.99191643],
       [10.        , 10.19802596, 10.44055703, 10.13198481,  3.        ,
        10.12182733],
       [10.        , 10.94408733, 10.44055703, 10.46179447,  3.        ,
        10.0263776 ]])

In [22]:
male_array_2 = np.array(data_male.loc[:, ['혈당', '수축기혈압', '이완기혈압', '총콜레스테롤',
                                            'HDL콜레스테롤', 'LDL콜레스테롤', '혈색소', '요단백']])
male_array_2

array([[1., 3., 3., ..., 4., 1., 1.],
       [1., 2., 1., ..., 2., 1., 1.],
       [1., 2., 1., ..., 4., 1., 1.],
       ...,
       [3., 1., 1., ..., 2., 1., 1.],
       [2., 1., 1., ..., 1., 1., 1.],
       [2., 1., 1., ..., 2., 1., 1.]])

In [23]:
np.save('male_array_1.npy', male_array_1)
np.save('male_array_2.npy', male_array_2)